spring:
  application:
    name: 'SimpleSpringBoot1'
server:
  port: 8080

eureka:
  instance:
#    Needs a host address passed in as an environment variable.
    ip-address: ${HOST}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    instance-id: ${HOST}:${spring.application.name}:${server.port}
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://ec2-54-160-145-160.compute-1.amazonaws.com:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: local

eureka:
  instance:
    ip-address: 127.0.0.12
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    hostname: 127.0.0.12
  client:
    service-url: # Connect to Eureka: try AWS, Docker, then localhost. If any aren't up, the app will throw an exception but should start up.
      defaultZone: http://ec2-54-160-145-160.compute-1.amazonaws.com:8761/eureka/,http://Discovery-Service:8761/eureka/,http://localhost:8761/eureka/