
spring:
  application:
    name: 'SimpleSpringBoot1'
server:
  port: 8080

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://ec2-54-160-145-160.compute-1.amazonaws.com:8761/eureka/,http://localhost:8761/eureka/